from __future__ import annotations

from dataclasses import asdict

from cvehunt.models import TraceEvent, WorkflowReport


FULL_PIPELINE_PHASES = [
    {
        "phase": "Collector",
        "goal": "Collect CVE metadata and local fixture context.",
        "implemented": True,
    },
    {
        "phase": "Researcher",
        "goal": "Classify the vulnerable surface and defensive hypothesis.",
        "implemented": True,
    },
    {
        "phase": "Harness Builder",
        "goal": "Build isolated vulnerable and patched environments from real dependencies.",
        "implemented": False,
    },
    {
        "phase": "PoC Developer",
        "goal": "Create a harness-scoped proof-of-concept for exploitability validation.",
        "implemented": False,
    },
    {
        "phase": "Fix Developer",
        "goal": "Generate or apply a candidate source fix.",
        "implemented": False,
    },
    {
        "phase": "Validator",
        "goal": "Compare vulnerable and patched/fixed behavior and capture evidence.",
        "implemented": True,
    },
    {
        "phase": "Judge",
        "goal": "Assess evidence, safety boundaries, and remediation efficacy.",
        "implemented": True,
    },
]


def render_markdown(report: WorkflowReport) -> str:
    data = asdict(report)
    cve = data["cve"]
    run = data["run"]
    finding = data["finding"]
    judgement = data["judgement"]
    evidence = data["evidence"]

    lines = [
        f"# CVEHunt Report: {cve['cve_id']}",
        "",
        f"Name: {cve['name']}",
        f"CVSS: {cve['cvss'] if cve['cvss'] is not None else 'unknown'}",
        f"KEV: {'yes' if cve['kev'] else 'no'}",
        f"Ecosystem: {cve['ecosystem']}",
        f"Run ID: {run['run_id']}",
        f"Model: {run['model']}",
        "",
        "## Finding",
        "",
        f"- Class: {finding['vulnerability_class']}",
        f"- Surface: {finding['impacted_surface']}",
        f"- Defensive hypothesis: {finding['defensive_hypothesis']}",
        "",
        "## Evidence",
        "",
    ]
    for item in evidence:
        lines.extend(
            [
                f"- Check: {item['check_name']}",
                f"  Vulnerable signal: {item['vulnerable_signal']}",
                f"  Patched signal: {item['patched_signal']}",
                f"  Passed: {'yes' if item['passed'] else 'no'}",
            ]
        )
    lines.extend(
        [
            "",
            "## Artifact Outcomes",
            "",
            "- Full exploit generated: no",
            "- Source patch generated: no",
            "- Scope: defensive fixture evidence and remediation guidance only",
            "",
            "## Judgement",
            "",
            f"Status: {judgement['status']}",
            f"Confidence: {judgement['confidence']:.2f}",
            f"Rationale: {judgement['rationale']}",
            "",
            "Remediation notes:",
            *[f"- {note}" for note in judgement["remediation_notes"]],
            "",
            "Safety notes:",
            *[f"- {note}" for note in judgement["safety_notes"]],
        ]
    )
    return "\n".join(lines)


def render_pipeline_status(
    report: WorkflowReport,
    events: list[TraceEvent],
) -> dict[str, object]:
    completed = {event.phase: event for event in events}
    stages = []
    for phase in FULL_PIPELINE_PHASES:
        event = completed.get(str(phase["phase"]))
        reached = event is not None
        stages.append(
            {
                **phase,
                "reached": reached,
                "status": "completed" if reached else "not_reached",
                "message": event.message if event else _not_reached_message(phase),
                "artifact": event.artifact if event else None,
            }
        )

    return {
        "cve_id": report.cve.cve_id,
        "run_id": report.run.run_id,
        "model": report.run.model,
        "overall_status": report.judgement.status,
        "confidence": report.judgement.confidence,
        "furthest_completed_stage": events[-1].phase if events else None,
        "requested_full_pipeline_completed": False,
        "exploit_generated": False,
        "fix_generated": False,
        "fix_validated": False,
        "notes": [
            "This run used the currently implemented synthetic fixture workflow.",
            "No real dependencies were downloaded for vulnerable/patched environment construction.",
            "No harness-scoped PoC or source fix was generated by this run.",
            "Remediation was assessed only as patched-version guidance plus synthetic differential evidence.",
        ],
        "stages": stages,
    }


def _not_reached_message(phase: dict[str, object]) -> str:
    if phase["implemented"]:
        return "Implemented but not reached in this run."
    return "Not implemented in the current CVEHunt pipeline."
